//Data add
export const STUDENT_ADD_REQUEST = "STUDENT_ADD_REQUEST";
export const STUDENT_ADD_SUCCESS = "STUDENT_ADD_SUCCESS";
export const STUDENT_ADD_FAILURE = "STUDENT_ADD_FAILURE";
export const STUDENT_ADDING = "STUDENT_ADDING";

//Data edit
export const STUDENT_EDIT_REQUEST = "STUDENT_EDIT_REQUEST";
export const STUDENT_EDIT_SUCCESS = "STUDENT_EDIT_SUCCESS";
export const STUDENT_EDIT_FAILURE = "STUDENT_EDIT_FAILURE";

//Data delete
export const STUDENT_DELETE_REQUEST = "STUDENT_DELETE_REQUEST";
export const STUDENT_DELETE_SUCCESS = "STUDENT_DELETE_SUCCESS";
export const STUDENT_DELETE_FAILURE = "STUDENT_DELETE_FAILURE";
